Real-time QA
UWRealityLab/xrcapstone24sp-team2 pull request #40
Opened 2024-05-19 18:59 UTC by junwang0510

- Prompt ChatGPT during the presentation (i.e., every 30 seconds) with the accumulated transcription.
- Indicate to the user that the generated questions are ready and enable users to interact with the questions during the speech.
- Refactored ‘TranscriptionLogger.cs’.

2024-05-20 20:08 UTC, zach8421 commented
Need to add the TranscriptionLogger.ResetTranscript() from the FullTranscription game object as an onclick() component to the Restart Button game object. Currently the Overall Average WPM and Section Averages don't reset.

2024-05-21 01:38 UTC, junwang0510 commented
fixed.

2024-05-21 15:36 UTC, zach8421 submitted a review, later dismissed

2024-05-21 22:01 UTC, kjy5 requested changes
- [ ] Hide motion graph until grading
- [ ] Slow down measurement frequency so that it doesn't bog down system (30 FPS)
- [ ] Move search bar to be on the podium (it's blocking the view of the audience
- [ ] Hide keyboard by default until needed
- [ ] (if possible) Make enter key run search and close the keyboard after
- [ ] Merge with main auditorium scene and apply to conference scene

2024-05-21 22:55 UTC, closed without merging